name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux, x64, Ubuntu]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Check Docker Group Membership
        run: id -nG

      - name: Add User to Docker Group
        run: sudo groupadd -f docker

      - name: Add User to Docker Group
        run: sudo usermod -aG docker $USER

      - name: Add User to Docker Group
        run: newgrp docker

      - name: Restart Docker
        run: sudo service docker restart

      - name: Check Docker Status
        run: sudo service docker status

      - name: Start Docker
        run: sudo service docker start


      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alvinbevan/new-image:1

      - name: Deploy to Kubernetes
        run: kubectl apply -f Deployment.yaml
        if: success()

      - name: Apply Service Account
        run: kubectl apply -f service.yaml
        if: success()
